services:
  backend:
    build: ./backend
    expose:
      - "8766"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8765:80"
    depends_on:
      - backend
    restart: always